# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sanbong_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# JWT
jwt.secret=sanbong_super_secret_key_must_be_at_least_32_chars
jwt.expiration=86400000

# Upload file (n?u sau này thêm upload ?nh sân)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
